name: ci

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set upNoede
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: check version node
      - run: node --version

      - name: Install Eslint
      - run: npm i eslint-plugin-import
      
      - name: Force Failure
        run: (exit 1)
